ffmpeg -y -i JaDaumenhoch_f.mp4 -filter_complex "[0:v]trim=duration=0.01,tpad=stop_mode=clone:stop_duration=1000000[v1];[0:v][v1]overlay=shortest=1" -c:a copy JaDaumenhoch_f_no_gesture.mp4
ffmpeg -y -i JaDaumenhoch_m.mp4 -filter_complex "[0:v]trim=duration=0.01,tpad=stop_mode=clone:stop_duration=1000000[v1];[0:v][v1]overlay=shortest=1" -c:a copy JaDaumenhoch_m_no_gesture.mp4
ffmpeg -y -i JaDaumenrunter_f.mp4 -filter_complex "[0:v]trim=duration=0.01,tpad=stop_mode=clone:stop_duration=1000000[v1];[0:v][v1]overlay=shortest=1" -c:a copy JaDaumenrunter_f_no_gesture.mp4
ffmpeg -y -i JaDaumenrunter_m.mp4 -filter_complex "[0:v]trim=duration=0.01,tpad=stop_mode=clone:stop_duration=1000000[v1];[0:v][v1]overlay=shortest=1" -c:a copy JaDaumenrunter_m_no_gesture.mp4
ffmpeg -y -i JaKopfJa_f.mp4 -filter_complex "[0:v]trim=duration=0.01,tpad=stop_mode=clone:stop_duration=1000000[v1];[0:v][v1]overlay=shortest=1" -c:a copy JaKopfJa_f_no_gesture.mp4
ffmpeg -y -i JaKopfJa_m.mp4 -filter_complex "[0:v]trim=duration=0.01,tpad=stop_mode=clone:stop_duration=1000000[v1];[0:v][v1]overlay=shortest=1" -c:a copy JaKopfJa_m_no_gesture.mp4
ffmpeg -y -i JaKopfNein_f.mp4 -filter_complex "[0:v]trim=duration=0.01,tpad=stop_mode=clone:stop_duration=1000000[v1];[0:v][v1]overlay=shortest=1" -c:a copy JaKopfNein_f_no_gesture.mp4
ffmpeg -y -i JaKopfNein_m.mp4 -filter_complex "[0:v]trim=duration=0.01,tpad=stop_mode=clone:stop_duration=1000000[v1];[0:v][v1]overlay=shortest=1" -c:a copy JaKopfNein_m_no_gesture.mp4
ffmpeg -y -i NeinDaumenhoch_f.mp4 -filter_complex "[0:v]trim=duration=0.01,tpad=stop_mode=clone:stop_duration=1000000[v1];[0:v][v1]overlay=shortest=1" -c:a copy NeinDaumenhoch_f_no_gesture.mp4
ffmpeg -y -i NeinDaumenhoch_m.mp4 -filter_complex "[0:v]trim=duration=0.01,tpad=stop_mode=clone:stop_duration=1000000[v1];[0:v][v1]overlay=shortest=1" -c:a copy NeinDaumenhoch_m_no_gesture.mp4
ffmpeg -y -i NeinDaumenrunter_f.mp4 -filter_complex "[0:v]trim=duration=0.01,tpad=stop_mode=clone:stop_duration=1000000[v1];[0:v][v1]overlay=shortest=1" -c:a copy NeinDaumenrunter_f_no_gesture.mp4
ffmpeg -y -i NeinDaumenrunter_m.mp4 -filter_complex "[0:v]trim=duration=0.01,tpad=stop_mode=clone:stop_duration=1000000[v1];[0:v][v1]overlay=shortest=1" -c:a copy NeinDaumenrunter_m_no_gesture.mp4
ffmpeg -y -i NeinKopfJa_f.mp4 -filter_complex "[0:v]trim=duration=0.01,tpad=stop_mode=clone:stop_duration=1000000[v1];[0:v][v1]overlay=shortest=1" -c:a copy NeinKopfJa_f_no_gesture.mp4
ffmpeg -y -i NeinKopfJa_m.mp4 -filter_complex "[0:v]trim=duration=0.01,tpad=stop_mode=clone:stop_duration=1000000[v1];[0:v][v1]overlay=shortest=1" -c:a copy NeinKopfJa_m_no_gesture.mp4
ffmpeg -y -i NeinKopfNein_f.mp4 -filter_complex "[0:v]trim=duration=0.01,tpad=stop_mode=clone:stop_duration=1000000[v1];[0:v][v1]overlay=shortest=1" -c:a copy NeinKopfNein_f_no_gesture.mp4
ffmpeg -y -i NeinKopfNein_m.mp4 -filter_complex "[0:v]trim=duration=0.01,tpad=stop_mode=clone:stop_duration=1000000[v1];[0:v][v1]overlay=shortest=1" -c:a copy NeinKopfNein_m_no_gesture.mp4
